### ISSUE TITLE
Motivate use of continuous delay distributions

### ISSUE THREAD

**Issue by sbfnk** [epiverse-trace/cfr#115]
In a few places it is now clarified that "we do not expect this difference to bias the estimates excessively". I think this is missing a rationale for *why* you do not expect this in the specific examples and when we would expect it to no longer be the case. Whether the difference biases estimates will depend on the specific use case, parameter values etc. so I think it would be important to provide some explanation to the reader.

**Comment by pratikunterwegs** [comment]
Thanks @sbfnk - will add these clarifications (still trying to understand the maths of this myself first).

**Comment by adamkucharski** [comment]
IIRC I linked to specific theory in one of the PRs, but the main point I think is that if we use a continuous distribution (normalised so PDF at integer values sums to 1) in place of a discrete one, we are assuming that the continuous pdf at a given integer value N is similar to the integral of that pdf from N to N+1 (ie. Discretised version). When the distribution is more spread out (ie. Longer delay with larger variance), the curve is flatter, so N and N+1 are more similar on average, and hence the error incurred with this assumption smaller than it would be for a very peaked distribution.

On top of this, because we're tallying up counts in the calculation, any underestimates and one end of the approximated distribution will also help cancel out overestimates at the other.

**Comment by pratikunterwegs** [comment]
Thanks @adamkucharski - I plugged some keywords from this into ChatGPT and it managed a decent explanation (complete with poor text art of distributions).
