### ISSUE TITLE
README images are missing

### ISSUE THREAD

**Issue by TimTaylor** [epiverse-trace/cfr#40]
Images in the rom the following lines do not appear for me in the README:
https://github.com/epiverse-trace/datadelay/blob/3a7cb2a98fe9eea85585215ee01e939ae98ae249/README.Rmd#L98-L99

**Comment by Bisaloo** [comment]
Thanks for the report!

I'm confused :thinking:. I assumed it was because these lines could not add untracked files:

https://github.com/epiverse-trace/datadelay/blob/3a7cb2a98fe9eea85585215ee01e939ae98ae249/.github/workflows/render_readme.yml#L57-L61

but I can't reproduce locally, even when changing my shell to `sh`.

**Comment by pratikunterwegs** [comment]
I can add this to my to-do for tomorrow if that's soon enough? There's also issue #38 that I could clean up at the same time
