### ISSUE TITLE
{epiparameter} integration

### ISSUE THREAD

**Issue by TimTaylor** [epiverse-trace/cfr#59]
I wonder if user-facing integration with {epiparameter} should be achieved in a similar way to the [work in superspreading](https://github.com/epiverse-trace/superspreading/blob/8061971d34241e257c7e6f57260bae0953225e30/R/probability_epidemic.R#L30). Here I believe @joshwlambert has moved towards the epidist object being an optional argument. I think this is a nice as it does not force the use of epidist objects on the user.

Note this is not a question of dependencies ({cfr} would still need to import {epiparameter} for internal use) but of API design and consistency across the various packages.

This likely warrants a wider discussion but raising here initially.

**Comment by pratikunterwegs** [comment]
Thanks - I do like Josh's integration. If I understand correctly, this would essentially bring back the `delay_pmf` argument that existed until I implemented the `epi_dist` argument in PR #22.

The question is what would users pass instead? If I have it right, it would have to be a function that wraps the PMF function for a distribution, so `function(x) stats::dgamma(x, shape, rate)`, or `function(x) stats::density(distribution, at = x)` for `<distributional>` or similar objects. This does offer the user choice, but is it conceptually any easier than working with {epiparameter}?

Still, if this is a strong ask I can assign myself to this issue - could you edit the title to reflect the changed goal?

**Comment by pratikunterwegs** [comment]
Thanks - yes, this change was made by Tim R a while ago in his initial implementation which I then took over to close PR #11 (unfortunately from our squash-merging days). I'm not entirely sure how he came round to using it, as the commits are not atomic.

The current API does have `<epidists>` as optional actually, but omitting them prevents using the package's main draw which is estimating severity while correcting for delays. One can still get a CFR estimate though it will be biased.

**Comment by pratikunterwegs** [comment]
I think we expect that users would use the catalogue, rather than defining their own parameters; this is the motivation for {epiparameter}. I caveat that by saying that we haven't had a lot of user engagement to map out their profiles, so I can't be sure.

> Anyway - this is why I think it's worth pondering a little more prior to any CRAN submission.
I imagine that {epiparameter} and {cfr} are both unlikely to head to CRAN much before the end of the year, so there's time to think about these issues. That said, it's important to get MVPs out rather than to get them just right, imo, to gain some visibility.

**Comment by pratikunterwegs** [comment]
Happy to hear more on this, but I'm going to go ahead and open a separate issue for re-instating the `delay_pmf` argument as suggested.

**Comment by joshwlambert** [comment]
Thanks @TimTaylor and @pratikunterwegs for raising and discussing this issue. I agree with Tim that this is the type of user-facing design decision that it would be good to "get right" before a CRAN release. 

Firstly, I think the use of `<epidist>` by {cfr} is different from {superspreading}. In {superspreading} the object is a vector for the parameter values (in that case $R$ and $k$), so it was reasoned that supplying two numbers is often simpler than users constructing an `<epidist>` to supply these. However, we (all three of us included) still felt the interoperability was important  so the extra argument (as shown in Tim's link in the message above) was added. It was added after `...` in order to make the users be explicit about supplying an `<epidist>`.

For {cfr} the `<epidist>` is being used for the distribution object and the parameter values, so the complexity is closer to an `<epidist>` object. If it is viewed that supplying an anonymous function would be within the capabilities of the user then I would agree with reimplementing the `delay_pmf` argument and moving `epidist` to behind an `...` at the end of the function definition. However, if we think this is likely beyond the R capabilities of the {cfr} audience it may be better to go with enforcing the use of `<epidist>` and facilitate the user by clearly explaining in documentation how these can be extracted from {epipmarameter}. 

Overall, I do not have a strong opinion. For this specific case I'm leaning towards the second option of forcing a user to supply an `<epidist>` as this is likely easier, and provides other benefits like handling discretised distributions (not sure if these can be used by {cfr}). 

Lastly, I recommend changing the name from `epi_dist` to `epidist` for consistency with other packages (e.g. {superspreading}) and with the name of the class.

**Comment by pratikunterwegs** [comment]
Thanks @joshwlambert for weighing in. @TimTaylor would it make more sense to put the `delay_pmf` argument at the end so that that is the alternative method? Advanced users can bypass the `epi_dist` argument in that case, while beginner users might want to use a delay distribution from a catalogue.

@joshwlambert - point taken about renaming `epi_dist` to `epidist` - will open an issue for this.

**Comment by pratikunterwegs** [comment]
Thanks Tim - I think {cfr} is supposed to stand alone as well, but definitely the main functionality is integration with delay distributions.

I think making a generic with methods could also be a good idea. Would it help to have methods for {distributional} and {distcrete} as well - are these widely used in epi do you think? I think the `<epidist>` only provides the PMF and the distribution parameters, so should work.

I'm focusing on renaming args and {epidemics} this week, so happy to hear thoughts at more leisure.

**Comment by pratikunterwegs** [comment]
@TimTaylor - do you have any further thoughts on this? @adamkucharski would you want to weigh in from the perspective of integration and also usability?

**Comment by adamkucharski** [comment]
I'd be happy with keeping the `epidist` object as required input for now – I think a common use case will be for users to either pull a parameter from the library (especially as this becomes more complete via WHO Collaboratory, Imperial efforts etc.), or to import directly from a literature estimate (in which case, it would generally need to pass through `epiparameter` to get the distributional parameters. The upcoming WHO workshop will be a good opportunity to get user feedback on this overall approach.

**Comment by pratikunterwegs** [comment]
Okay, thanks - I'll put the related issue #62 on hold for now. When is the WHO workshop again, for an idea of timelines?

**Comment by adamkucharski** [comment]
> When is the WHO workshop again, for an idea of timelines?

Planned for second half of September. But could reach out to relevant groups earlier if useful.

**Comment by pratikunterwegs** [comment]
> > When is the WHO workshop again, for an idea of timelines?
> 
> Planned for second half of September. But could reach out to relevant groups earlier if useful.

Thanks - I guess it depends on whether we want to get {cfr} headed to CRAN before the workshop. If so, it would be good to submit it with this functionality rather than change the interface shortly after the submission; again, only if we think it's likely to be useful.

**Comment by adamkucharski** [comment]
I think we should proceed as-is, so it's ready for people to use, given any (unlikely) need for future tweaks to inputs would likely come further down the line.

**Comment by pratikunterwegs** [comment]
Thanks! Issue #62 is on hold then. I'll keep this issue open and pin it for future reference.

**Comment by pratikunterwegs** [comment]
Closing this as fixed by #88.
