### ISSUE TITLE
Remove basic plotting sections in vignettes

### ISSUE THREAD

**Issue by pratikunterwegs** [epiverse-trace/cfr#65]
I'm wondering about adding these [plotting] sections that are about plotting the data prior to applying the functions, it's nice but maybe the content of the vignettes should go a bit more straight to the point of demonstrating the functionality of the package and the plotting that's not showcasing the outputs of the functions would fit better on a tutorial or learning platform like Applied Epi?

_Originally posted by @CarmenTamayo in https://github.com/epiverse-trace/cfr/pull/55#discussion_r1277651172_

**Comment by jamesmbaazam** [comment]
Thanks, @CarmenTamayo, you have a valid point. I think just plotting the data without any form of discussion could make the plots look out of place. It's interesting because it is similar to viewing the "head" of the data in most vignettes. Why does the former look out of place? (just thinking out loud). 

Generally, data analysis good practice dictates first exploring the data (viewing the head, plotting it, etc.). I am not totally convinced that plotting the data in our vignettes to explore it before applying the package's functionality is necessarily bad. I think if anything, it establishes good practice. The only thing I would suggest here is to add a few statements about what the data looks like and why it is suitable for the purpose.

**Comment by pratikunterwegs** [comment]
Fixed in #104
