### ISSUE TITLE
Methods for low-frequency reporting

### ISSUE THREAD

**Issue by pratikunterwegs** [epiverse-trace/cfr#76]
This issue is for a discussion of whether {cfr} should have methods that can account for low-frequency reporting of cases and deaths, such as weekly reporting of Covid data in the example below.

> This looks more plausible for most countries, but looking at the remaining 100% estimates (i.e. Spain, Germany, France, Ukraine), it's happening because the data for those four countries are only weekly, but the underascertainment algorithm (and underlying CFR calculation) is designed for daily data, which is why it's returning an erroneous result. I'd therefore suggest we omit these countries with a brief note to user about why?

_Originally posted by @adamkucharski in https://github.com/epiverse-trace/cfr/pull/74#discussion_r1293864909_

**Comment by CarmenTamayo** [comment]
I would like to contribute to this issue based on the data from one of the case studies, an outbreak of Marburg in Equatorial Guinea (see [report by WHO](https://www.who.int/emergencies/disease-outbreak-news/item/2023-DON472#:~:text=On%208%20June%202023%2C%20after,as%20per%20the%20WHO%20recommendations.) where I got the data from)

These data have the following characteristics:

- Date of onset: weeks, reported at a regular interval
- Total number of deaths up to specific points during the outbreak, at an irregular interval

Ideally, `cfr` would provide a method to allow the users to input the total number of deaths up to a certain point of the outbreak manually, rather than this being taken from a column on the dataset (which is not available in this Marburg example), while also being able to take onset weeks as input, as well as days.

Other options that might be found in situation reports:

- Daily onsets and weekly deaths
- Daily onsets and total deaths
- Irregular reporting of onset and deaths

@Karim-Mane @adamkucharski

**Comment by pratikunterwegs** [comment]
Thanks @CarmenTamayo - I've pushed the experimental low-res method for daily cases and total deaths that we discussed as the function `cfr_static_lowres()` on the `dev/lowres` branch - it's basically a tweak of `cfr_static()` with delay correction. Happy to tinker a bit more as this seems to be a real use case.

**Comment by adamkucharski** [comment]
Ideally, we'd handle aggregation with an appropriate inference method (because the epidemic has to follow some underlying transmission process, which should tell us something about the underlying daily incidence generating the weekly data). EpiEstim now has an EM function that can estimate daily incidence from weekly data: https://mrc-ide.github.io/EpiEstim/articles/EpiEstim_aggregated_data.html. Maybe EpiNow2 has something similar @sbfnk @jamesmbaazam ?

If we can identify a common situation where a particular aggregation is used, could aim to build something around that, accounting for the relevant censoring. But feels like there could potentially be quite a lot of different edge cases (which would favour a case study discussing concepts over multiple additional functions)?

**Comment by pratikunterwegs** [comment]
Thanks @adamkucharski - currently Carmen has laid out the aggregation she's found in data, e.g. from Marburg, so happy to work on this in the near future. Overall though, perhaps something for a second release? Current functionality is a good MVP.

**Comment by pratikunterwegs** [comment]
Addressed in #117.
